spring.application.name=adminportal
server.port=8099
server.servlet.context-path=/adminportal
spring.thymeleaf.cache=false


# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection
spring.datasource.url=${DB_URL}

# Set maximum allowed size for uploaded files
spring.servlet.multipart.max-file-size=50MB

# Set maximum allowed size for form-data requests
spring.servlet.multipart.max-request-size=50MB



# Username and secret
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}




# ===============================
# = JPA / HIBERNATE
# ===============================

# Use spring.jpa.properties.* for Hibernate native properties (the prefix is
# stripped before adding them to the entity manager).

# Show or not log for each sql query
spring.jpa.show-sql=false

# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
