spring.application.name=breadbitt
spring.thymeleaf.cache=false
server.port=8098
spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8


# Set maximum allowed size for uploaded files
spring.servlet.multipart.max-file-size=50MB

# Set maximum allowed size for form-data requests
spring.servlet.multipart.max-request-size=50MB


# ======================
# = DATA SOURCE
# ======================

# Set database connection configurations
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =======================
# = JPA / HIBERNATE 
# =======================

# Show SQL queries in logs
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.thymeleaf=DEBUG
spring.thymeleaf.mode=LEGACYHTML5

# Hibernate ddl auto: update schema based on entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
open-in-view=true

# Database dialect for Hibernate
 spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
 
 
 
spring.mail.host=smtp.gmail.com
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
support.email=${SUPPORT_EMAIL}
